on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates Unsplash stats and blog posts
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Collect and update markdown with Unsplash stats
    - name: Gathering Unsplash stats
      uses: gabrieluizramos/unsplash-stats-workflow@master
      with:
        username: gabrieluizramos
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        template: table

    - name: Updating blog posts
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: BLOG
        feed_list: "https://gabrieluizramos.com.br/feed.xml"

