on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: A job to print Unsplash Stats
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Collect and update markdown with Unsplash stats
    - name: Gathering Unsplash stats
      uses: gabrieluizramos/unsplash-stats-workflow@master
      with:
        file: './README.md'
        username: gabrieluizramos
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    
    # Commit/Push to your repo after changing
    - name: Updating repo
      uses: EndBug/add-and-commit@v5
      with:
        add: './README.md'
        author_name: gabrieluizramos
        author_email: gabriel.luiz.ramos@gmail.com
        message: "README updated with Unsplash stats"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Updating blog posts
      uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://gabrieluizramos.com.br/feed.xml"

